NCD/Controllers/CriminalController.cs
using System.Web;
using System.Web.Mvc;
using NCD.Application.Domain;
using NCD.Application.Services;
using NCD.Models;
using Ninject;
using System.Linq;

namespace NCD.Controllers
{
    public class CriminalController : Controller
    {
        [Inject]
        public ISearchService SearchService { get; set; }

        [Inject]
        public IEmailService EmailService { get; set; }

        public ActionResult Index()
        {
            if (this.Request.IsAuthenticated)
            {
                var model = new SearchViewModel
                {
                    Email = this.HttpContext.GetOwinContext().Request.User.Identity.Name,
                };

                return View(model);
            }
            return RedirectToAction("Index", "");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Search(SearchViewModel model)
        {
            if (ModelState.IsValid)
            {
                var searchRequest = new SearchRequest
                {
                    Email = model.Email,
                    MaxNumberResults = model.MaxNumberResults.Value,
                    Name = model.Name,
                    Sex = model.Sex,
                    AgeFrom = model.AgeFrom,
                    AgeTo = model.AgeTo,
                    HeightTo = model.HeightTo,
                    HeightFrom = model.HeightFrom,
                    WeightFrom = model.WeightFrom,
                    WeightTo = model.WeightTo
                };

                var criminals = SearchService.SearchCriminal(searchRequest);
                EmailService.Send(searchRequest.Email, criminals);

                if (!criminals.Any())
                {
                    return View("Negate");
                }
                
                    return View("Confirmation");
                
            }

            return View("Index", model);
        }
    }
}

NCD/Views/Shared/_Header.cshtml
<div class="header">
    <img src="~/Content/img/spectre.png" class="logo top-block"/>

    <h2 class="top-block">National Criminals Database</h2>
    
    @if (this.Request.IsAuthenticated)
    {

        if (ViewBag.Title == "Manage")
        {
            using (Html.BeginForm("Index", "Criminal", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                <button type="submit" class="button button-new">Criminal</button>
            }
        }
        else
        {
            using (Html.BeginForm("Index", "Manage", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                <button type="submit" class="button button-new">Manage</button>
            }
        }

        using (Html.BeginForm("LogOff", "Account", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <button type="submit" class="button button-danger">Logout</button>

        }

    }
</div>

NCD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Criminals</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    <div class="container">
        @RenderSection("header", false)
        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>